@name = "Prueba producto"
@description = "Descripción de prueba"
@category = "Categoria de prueba"
@price = 10.99

POST  http://localhost:5088/api/products
Content-Type: application/json

{
    "name": {{name}},
    "description": {{description}},
    "category": {{category}},
    "price": {{price}}
}