@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsIm5iZiI6MTY5MTM3MzU4NywiZXhwIjoxNjkzOTY1NTg3LCJpYXQiOjE2OTEzNzM1ODcsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTA4OCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTA4OCJ9.AlJcM930ti8OhtQAroPr_bLC17Ti60fumPFzZGnJLxc
GET http://localhost:5088/api/products
Authorization: Bearer {{token}}