@id = 4c424f81-a9b6-4f89-adf8-eb7fb4a57e19
@name = "Producto de prueba modified"
@description = "Descripción de prueba"
@category = "Categoria de prueba"
@price = 19.99

PUT http://localhost:5088/api/products/{{id}}
Content-Type: application/json

{
    "name": {{name}},
    "description": {{description}},
    "category": {{category}},
    "price": {{price}}
}