@id = 18

GET http://localhost:5088/api/supplies/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTY5MTQ1NzIwNCwiZXhwIjoxNjk0MDQ5MjA0LCJpYXQiOjE2OTE0NTcyMDQsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTA4OCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTA4OCJ9.r1Adi5KHOSoR_URspYTEKCjoR5HRcQe4KSXNcrzbHQc