

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTY5MTU1NTYwNSwiZXhwIjoxNjk0MTQ3NjA0LCJpYXQiOjE2OTE1NTU2MDUsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTA4OCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTA4OCJ9.Yq-zGLRqbEFv2GxPMH2nd93MKssQvLcj4-VEF2AV-eQ 

POST  http://localhost:5088/api/orders/markasdelivered
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "orderId": 2
}